#spring.application.name=ShoppingListApp
#
## H2 Configuration
#spring.datasource.url=jdbc:h2:mem:shoppingdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#
## JPA/Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## Spring Security
#spring.security.user.name=myusername
#spring.security.user.password=mypassword


# Spring Boot Configuration

spring.application.name=ShoppingListApp

# Database Configuration (Environment Variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Configuration
spring.security.user.name=${APP_SECURITY_USER_NAME:myusername}
spring.security.user.password=${APP_SECURITY_USER_PASSWORD:mypassword}
